#!/usr/bin/env python3
# Copyright (c) 2026 Brad Root
# SPDX-License-Identifier: MPL-2.0
"""Regenerate lurkerkit/LEDGER.md: what has been ported from LurkerKit, and what has drifted.

    python3 lurkerkit/tools/ledger.py [--ios ../lurker-ios] [--check]

Everything is read from git at the pinned commit (`ledger.json`'s "pin"), never from the
lurker-ios working tree, so the answer does not depend on which branch happens to be checked
out there. A source file counts as ported when its Kotlin twin exists; a test counts as ported
when a `fun` of the same name exists in the twin test class — by NAME, so a port-only test
can't stand in for a missing one.

`--check` exits 1 if a ported file has changed in lurker-ios `origin/main` since the pin, or a
ported test file is missing tests the ledger doesn't account for.
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

KIT = Path(__file__).resolve().parent.parent
SRC = "LurkerKit/Sources/LurkerKit/"
TESTS = "LurkerKit/Tests/LurkerKitTests/"
KOTLIN_NAMES = {"Client/JSON.swift": "client/Json.kt"}


def git(ios, *args):
    return subprocess.run(
        ["git", "-C", str(ios), *args], check=True, capture_output=True, text=True
    ).stdout


def swift_test_names(source):
    """XCTest methods (`func testFoo()`) and Swift Testing cases (`@Test(...) func foo()`)."""
    names = re.findall(r"func (test\w+)\s*\(", source)
    # By line rather than one regex over the file: a display name is a string literal that may
    # hold anything, and a stray quote in a comment derails any attempt to skip over them.
    lines = source.splitlines()
    for index, line in enumerate(lines):
        if not re.search(r"@Test\b", line):
            continue
        for candidate in lines[index:index + 6]:
            # The declaration, not a "func" inside the display name: nothing but modifiers before it.
            found = re.match(r"\s*(?:@Test\b(?:\(.*\))?\s*)?(?:\w+\s+)*func\s+(\w+)\s*\(", candidate)
            if found:
                if found.group(1) not in names:
                    names.append(found.group(1))
                break
    return names


def kotlin_path(swift):
    if swift in KOTLIN_NAMES:
        return KOTLIN_NAMES[swift]
    directory, name = swift.split("/")
    return f"{directory.lower()}/{name[:-len('.swift')]}.kt"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ios", default=str(KIT.parent.parent / "lurker-ios"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    config = json.loads((KIT / "tools/ledger.json").read_text())
    pin = config["pin"]
    tranches = config["tranches"]
    tranche_of = {f: t["id"] for t in tranches for f in t["files"]}
    notes = config.get("notes", {})
    test_notes = config.get("testNotes", {})

    listing = git(args.ios, "ls-tree", "-r", "--name-only", pin, "LurkerKit/").splitlines()
    sources = sorted(p[len(SRC):] for p in listing if p.startswith(SRC) and p.endswith(".swift"))
    tests = sorted(p[len(TESTS):] for p in listing if p.startswith(TESTS) and p.endswith(".swift"))

    # Drift: what moved on lurker-ios main since the pin.
    try:
        drifted = set(git(args.ios, "diff", "--name-only", pin, "origin/main", "--", "LurkerKit/").split())
    except subprocess.CalledProcessError:
        drifted = set()

    problems = []
    out = []
    out.append("# LurkerKit port ledger\n")
    out.append("Generated by `tools/ledger.py` — edit `tools/ledger.json`, not this file.\n")
    pin_line = git(args.ios, "log", "-1", "--format=%h (%cs) %s", pin).strip()
    out.append(f"**Pinned to lurker-ios `main` at {pin_line}.**\n")

    main_dir = KIT / "src/main/kotlin/net/amiantos/lurkerkit"
    test_dir = KIT / "src/test/kotlin/net/amiantos/lurkerkit"

    unassigned = [s for s in sources if s not in tranche_of]
    if unassigned:
        problems.append(f"no tranche for: {', '.join(unassigned)}")

    total_lines = ported_lines = 0
    rows_by_tranche = {t["id"]: [] for t in tranches}
    for swift in sources:
        lines = git(args.ios, "show", f"{pin}:{SRC}{swift}").count("\n")
        ported = (main_dir / kotlin_path(swift)).exists()
        total_lines += lines
        ported_lines += lines if ported else 0
        status = "ported" if ported else "—"
        note = notes.get(swift, "")
        if ported and SRC + swift in drifted:
            status = "ported, **drifted**"
            problems.append(f"{swift} changed on lurker-ios main since the pin")
        rows_by_tranche.setdefault(tranche_of.get(swift, "?"), []).append(
            f"| `{swift}` | {lines} | {status} | {note} |"
        )

    out.append(f"Sources: **{ported_lines:,} of {total_lines:,}** Swift lines ported.\n")
    out.append("## Sources\n")
    for tranche in tranches:
        rows = rows_by_tranche[tranche["id"]]
        done = sum("| ported" in r for r in rows)
        out.append(f"### {tranche['id']} — {tranche['title']} ({done}/{len(rows)})\n")
        if tranche.get("about"):
            out.append(tranche["about"] + "\n")
        out.append("| Swift file | Lines | Status | Notes |\n|---|---:|---|---|")
        out.extend(rows)
        out.append("")
    if "?" in rows_by_tranche:
        out.append("### Unassigned\n\n| Swift file | Lines | Status | Notes |\n|---|---:|---|---|")
        out.extend(rows_by_tranche["?"])
        out.append("")

    out.append("## Tests\n")
    out.append(
        "Matched by method name. *Waiting* tests need a type that is not ported yet; *dropped* ones"
        " have no meaning on this platform. Both are named, with the reason, in `ledger.json`.\n"
    )
    out.append("| Swift test file | Tests | Ported | Waiting | Dropped | Notes |\n|---|---:|---:|---:|---:|---|")
    swift_total = kotlin_total = 0
    for test in tests:
        swift_names = swift_test_names(git(args.ios, "show", f"{pin}:{TESTS}{test}"))
        twin = test_dir / (test[:-len(".swift")] + ".kt")
        kotlin_names = set(re.findall(r"fun (\w+)\s*\(", twin.read_text())) if twin.exists() else set()
        entry = test_notes.get(test, {})
        waiting = set(entry.get("waiting", []))
        dropped = set(entry.get("dropped", []))
        have = [n for n in swift_names if n in kotlin_names]
        swift_total += len(swift_names)
        kotlin_total += len(have)
        if twin.exists():
            unexplained = [n for n in swift_names if n not in kotlin_names and n not in waiting | dropped]
            if unexplained:
                problems.append(f"{test}: not ported and not accounted for: {', '.join(unexplained)}")
            stale = sorted((waiting | dropped) & kotlin_names) + sorted((waiting | dropped) - set(swift_names))
            if stale:
                problems.append(f"{test}: listed as waiting/dropped but ported or gone: {', '.join(stale)}")
            if TESTS + test in drifted:
                problems.append(f"{test} changed on lurker-ios main since the pin")
        out.append(
            f"| `{test}` | {len(swift_names)} | {len(have) if twin.exists() else '—'} "
            f"| {len(waiting) or ''} | {len(dropped) or ''} | {entry.get('note', '')} |"
        )
    out.append("")
    out.insert(4, f"Tests: **{kotlin_total:,} of {swift_total:,}** ported.\n")

    (KIT / "LEDGER.md").write_text("\n".join(out))
    for problem in problems:
        print(f"⚠ {problem}", file=sys.stderr)
    print(f"sources {ported_lines}/{total_lines} lines · tests {kotlin_total}/{swift_total}")
    if args.check and problems:
        sys.exit(1)


if __name__ == "__main__":
    main()
